name: location_picker_flutter_map
description: Package that provides Place search and Location picker for flutter maps with alot of cusomizations using Open Street Map
version: 1.0.2
homepage: https://github.com/Michael-M-aher/location_picker_flutter_map

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^2.2.0
  geolocator: ^9.0.1
  http: ^0.13.5
  intl: ^0.17.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter