name: flutter_location_search
description: Package that provides Place search with history of latest location searched using Open Street Map. It is easy to custom and can be displayed in fullscreen or overlay mode
version: 2.0.0
homepage: https://github.com/KomInc/flutter_location_search
license: MIT

environment:
  sdk: '>=3.3.0-0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  shared_preferences: ^2.0.16
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  json_serializable: ^6.8.0